version: "3.8"
services: 
    redis:
        image: postgres
        container_name: postgresql
        ports:
            - 5432:5432
        volumes:
            - ./data:/var/lib/postgresql/data
        environment: 
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        restart: unless-stopped