version: "3.8"
services: 
    redis:
        image: redis
        container_name: redis
        ports:
            - 6379:6379
        volumes:
            - ./data:/data
        restart: unless-stopped